name: dairy_app
description: Dairy farm app (Android & iOS)
publish_to: "none"

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

  # State management & UI helpers
  provider: ^6.0.5
  table_calendar: ^3.0.9
  image_picker: ^1.2.0
  intl: ^0.20.2
  flutter_upi_india: ^1.0.1
  razorpay_flutter: ^1.3.9
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - .env