name: dairy_app
description: Dairy farm app (Android & iOS)
publish_to: "none"

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.8.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.2.0

  # State management & UI helpers
  provider: ^6.0.5
  table_calendar: ^3.0.9
  image_picker: ^0.8.7+5
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
